In [63]:
import numpy as np

In [64]:
A = np.zeros((5, 5))

# Հոսքերի մատրից

In [65]:
indices = np.array([
[0, 1],
[0, 2],
[1, 3],
[2, 3],
[3, 4],
[0, 4]
])

# Հարևանության մատրից

In [66]:
A[indices[:, 0], indices[:, 1]] = 1
A

array([[0., 1., 1., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [39]:
all_A = np.zeros((0, 5, 5))

In [40]:
tmp = A.copy()

while True:
    
    all_A = np.concatenate((all_A, tmp[None]))
    
    tmp = A@tmp
    
    if tmp.sum() == 0:
        break


# Հասանելիության մատրից

In [61]:
B = all_A.sum(axis=0)
B

array([[0., 1., 1., 2., 3.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

# C մատրից

In [60]:
C = (B > 0).astype(int)
C

array([[0, 1, 1, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

# D մատրից

In [59]:
D = ((C == 1) & (C.T == 1)).astype(int)
D

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# Մուտքային գագաթներ

In [57]:
in_edges = np.where(np.all(A == 0, axis=0))
in_edges

(array([0]),)

# Ելքային գագաթներ

In [56]:
out_edges = np.where(np.all(A == 0, axis=1))
out_edges

(array([4]),)

# Գագաթների ռանգ

In [55]:
sigma = all_A.sum(axis=1).max(axis=0)
sigma

array([0., 1., 1., 2., 2.])

# Միջանկյալ գագաթներ

In [85]:
tmp = np.array(list(set(np.arange(A.shape[0])) - (set(in_edges[0].tolist()) | set(out_edges[0].tolist()) )))
tmp

array([1, 2, 3])